using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Text;

namespace TheOrigin.Framework.AOP
{
    public interface ITypeFactory
    {
        // configuration.
        ITypeFactory AsPublicClass();
        ITypeFactory AsInterface();
        ITypeFactory AsTypeAttributes(TypeAttributes Attributes);
        ITypeFactory FromParent<T>() where T : class;
        ITypeFactory FromParent(Type Parent);
        ITypeFactory ImplementInterface<TInterface>();
        ITypeFactory ImplementInterface(Type Interface);
        ITypeFactory AutoGenerateDefaultConstructor();

        // service.
        void Generate();
        IConstructorFactory CreateConstructor(params Type[] ConstructorTypes);
        IPropertyFactory CreateProperty(string PropertyName, Type PropertyType);
        IMethodFactory CreateMethod(string MethodName);
        Type GetTypeFromFactory();
    }
}
